---
title: "Bar chart creation"
author: "Joan Claverol - Data analytics mentor"
date: "6/5/2019"
output: 
  html_document:
    toc: true
    fig_align: center
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE)
```

## Give shape to the data with `dplyr`

Load  and prepare the data:

```{r echo=FALSE}
# libraires
if (require(pacman) == FALSE) {
  install.packages("pacman")
}
pacman::p_load(tidyverse, kableExtra)

# load data
ex_prod <- read_csv("../data/existingproductattributes2017.2.csv")

# analysing plto
glimpse(ex_prod)
```

Using `dplyr` to prepare the data: 

- Create the **total volume, total number of products, mean profit percentage and total profits** for each category: 

```{r}
ex_prod %>%
  group_by(ProductType) %>%
  summarise(
    Total_Volume = sum(Volume), 
    Number_Products = n(),
    Median_Profit_Perc = round(median(ProfitMargin),2),
    Median_Price_Perc = round(median(Price) ,2)
    ) %>%
  mutate(
    Total_Profits = Median_Profit_Perc*Median_Price_Perc*Total_Volume,
    Total_Profits_Dol = paste(round((Total_Profits), 0),"$")
    ) %>% 
  arrange(desc(Total_Volume)) -> categories_analysis 

kable(categories_analysis) %>% 
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

## Building the plot

1. Create the geometries 

```{r fig.align='center'}
p1 <- categories_analysis %>%
  arrange(Total_Profits) %>%
   ggplot(aes(x = reorder(ProductType, Total_Profits))) +
    geom_col(aes(y = Total_Profits), fill = "gold") +
    geom_col(aes(y = -Total_Volume), fill = "dodgerblue3") +
    geom_label(aes(x = ProductType, y = Total_Profits, 
                   label = Total_Profits_Dol),
               hjust = 0, 
               vjust = 0.4, 
               colour = "goldenrod3", 
               fill = NA, 
               label.size = NA, 
               size = 3.5) +
    geom_label(aes(x = ProductType, y = -Total_Volume, 
                   label = round(Total_Volume, 0)),
               hjust = 1, 
               vjust = 0.4, 
               colour = "dodgerblue4", 
               fill = NA, 
               label.size = NA, 
               size = 3.5)
p1
```

2. Turn the plot 

```{r fig.align='center'}
p2 <- p1 +
  coord_flip()
p2
```

3. Define the dimensions 

```{r fig.align='center'}
p3 <- p2 +
  scale_y_continuous(limits = c(-80000, 650000), labels = NULL)
p3
```

4. Add titles and personalize the theme

```{r fig.align='center'}
# Create a graph to understand Blackwell's business
p4 <- p3 +
  labs(title = "Blackwell overview",
         subtitle = "Total Volume (items) vs Total Profits ($)") +
  theme_void()
p4
```

5. Place the titles and plot information

```{r fig.align='center'}
p5 <- p4 +
theme(axis.title.x = element_blank(), 
           axis.title.y = element_blank(), 
           axis.text.y = element_text())
p5
```

